apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: superflat
spec:
  containers:
    - image: busybox
      name: pvc-inspector
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
