apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
    limits:
      storage: 4Gi
